"""Add ServiceableArea model

Revision ID: 7c9fb179af15
Revises: 6574e8e5
Create Date: 2025-04-09 20:31:01.508929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9fb179af15'
down_revision: Union[str, None] = '6574e8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serviceable_areas',
        sa.Column('pincode', sa.String(length=10), nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
        sa.Column('added_by_admin_id', sa.String(length=36), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['added_by_admin_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('pincode')
    )
    op.create_index('ix_serviceable_areas_pincode', 'serviceable_areas', ['pincode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_serviceable_areas_pincode', table_name='serviceable_areas')
    op.drop_table('serviceable_areas')
    # ### end Alembic commands ###
